version: '3'
services:
  grocy:
    image: "linuxserver/grocy"
    container_name: grocy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angeles"
    labels:
      traefik.enable: "true"
#      traefik.frontend.priority: "50"
      traefik.frontend.rule: "Host:house.wooster.xyz"
      traefik.port: "80"
      traefik.docker.network: "plexguide"
    restart: unless-stopped
    networks:
      - jarvis
    volumes:
      - /opt/appdata/grocy:/config

  barcodebuddy:
#    build:
#      context: /opt/barcodebuddy-docker
    #   args:
    #     BUILD_DATE: "test"
    #     VERSION: "0.1"
    image: f0rc3/barcodebuddy-docker
    container_name: barcodebuddy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angeles"
    labels:
      traefik.enable: "true"
#      traefik.frontend.priority: "10"
      traefik.frontend.rule: "Host:barcodebuddy.wooster.xyz"
      traefik.port: "80"
      traefik.docker.network: "plexguide"
    restart: unless-stopped
#    ports:
#      - "882:80"
#      - "47631:47631"
    networks:
      - jarvis
    volumes:
      - /opt/appdata/barcodebuddy:/config

  nextcloud_db:
    image: linuxserver/mariadb
    container_name: nextcloud_db
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angeles"
      MYSQL_ROOT_PASSWORD: "PcwJ9Qd5DT"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "nextcloud"
    restart: unless-stopped
    networks:
      - jarvis
    ports:
      - "3306:3306"
    volumes:
      - /opt/appdata/nextcloud_db:/config

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    labels:
      traefik.enable: "false"
      traefik.frontend.rule: "Host:sqladmin.wooster.xyz"
      traefik.port: "80"
      treafik.network: "plexguide"
    restart: unless-stopped
    networks:
      - jarvis
    ports:
      - "747:80"
    volumes:
      - /opt/appdata/phpmyadmin:/sessions

  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angeles"
    labels:
      traefik.enable: "true"
      traefik.protocol: "https"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:files.wooster.xyz"
      traefik.port: "443"
      traefik.docker.network: "plexguide"
    restart: unless-stopped
    networks:
      - jarvis
    volumes:
      - /opt/appdata/nextcloud:/config
      - /mnt/fillmore/nextcloud:/data

  magic_mirror:
    image: bastilimbach/docker-magicmirror
    container_name: magic-mirror
    environment:
      TZ: "America/Los_Angeles"
    restart: unless-stopped
    networks:
      - jarvis
    ports:
      - "664:8080"
    volumes:
      - /opt/appdata/magic_mirror/config:/opt/magic_mirror/config
      - /opt/appdata/magic_mirror/modules:/opt/magicmirror/modules
      - /etc/localtime:/etc/localtime:ro

  grafana:
    image: grafana/grafana
    container_name: grafana
#    user: "1000"
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:grafana.wooster.xyz"
      traefik.port: "3000"
      traefik.docker.network: "plexguide"
    restart: unless-stopped
    networks:
      - jarvis
#    ports:
#      - "3000:3000"
    volumes:
#      - /opt/appdata/grafana/config:/etc/grafana
#      - /opt/appdata/grafana/data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro

  foldingathome:
    image: linuxserver/foldingathome
    container_name: foldingathome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    networks:
      - jarvis
    volumes:
      - /opt/appdata/foldingathome:/config
    ports:
      - 7396:7396
      - 36330:36330 #optional
    restart: unless-stopped

#  samba:
#    image: dperson/samba
#    container_name: samba
#    environment:
#      USERID: 1000
#      GROUPID: 1000
#      TZ: "America/Los_Angeles"
#      NMBD: "False"
#      RECYCLE: "False"
##      USER: "karl;xiaohudze"
#      SHARE: "opt;/opt;yes;no;no;all"
#    restart: unless-stopped
#    networks:
#      - jarvis
#    ports:
#      - "139:139/tcp"
#      - "445:445/tcp"
#    volumes:
#      - /mnt/fillmore:/jarvis
#      - /opt:/opt:z
#    command: '-s "opt;/opt;yes;no;no;all"'

networks:
  jarvis:
    external:
      name: plexguide
