version: '3'
services:
  grocy:
    image: "linuxserver/grocy"
    container_name: grocy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angeles"
    labels:
      traefik.enable: "true"
#      traefik.frontend.priority: "50"
      traefik.frontend.rule: "Host:house.wooster.xyz"
      traefik.port: "80"
      traefik.docker.network: "plexguide"
    restart: unless-stopped
    networks:
      - jarvis
    volumes:
      - /opt/appdata/grocy:/config

  barcodebuddy:
    build:
      context: /opt/barcodebuddy-docker
    #   args:
    #     BUILD_DATE: "test"
    #     VERSION: "0.1"
    image: woosterinitiative/barcodebuddy-docker:v1
    container_name: barcodebuddy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angeles"
    labels:
      traefik.enable: "true"
#      traefik.frontend.priority: "10"
      traefik.frontend.rule: "Host:barcodebuddy.wooster.xyz"
      traefik.port: "80"
      traefik.docker.network: "plexguide"
    restart: unless-stopped
#    ports:
#      - "882:80"
#      - "47631:47631"
    networks:
      - jarvis
    volumes:
      - /opt/appdata/barcodebuddy:/config

  nextcloud_db:
    image: linuxserver/mariadb
    container_name: nextcloud_db
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angeles"
      MYSQL_ROOT_PASSWORD: "PcwJ9Qd5DT"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "nextcloud"
    restart: unless-stopped
    networks:
      - jarvis
    ports:
      - "3306:3306"
    volumes:
      - /opt/appdata/nextcloud_db:/config

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    labels:
      traefik.enable: "false"
      traefik.frontend.rule: "Host:sqladmin.wooster.xyz"
      traefik.port: "80"
      treafik.network: "plexguide"
    restart: unless-stopped
    networks:
      - jarvis
    ports:
      - "747:80"
    volumes:
      - /opt/appdata/phpmyadmin:/sessions

  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Los_Angeles"
    labels:
      traefik.enable: "true"
      traefik.protocol: "https"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:files.wooster.xyz"
      traefik.port: "443"
      traefik.docker.network: "plexguide"
    restart: unless-stopped
    networks:
      - jarvis
    volumes:
      - /opt/appdata/nextcloud:/config
      - /mnt/fillmore/nextcloud:/data

  magic_mirror:
    image: bastilimbach/docker-magicmirror
    container_name: magic-mirror
    environment:
      TZ: "America/Los_Angeles"
    restart: unless-stopped
    networks:
      - jarvis
    ports:
      - "664:8080"
    volumes:
      - /opt/appdata/magic_mirror/config:/opt/magic_mirror/config
      - /opt/appdata/magic_mirror/modules:/opt/magicmirror/modules
      - /etc/localtime:/etc/localtime:ro

networks:
  jarvis:
    external:
      name: plexguide
