- hosts: localhost
  gather_facts: False
  tasks:

  - name: Create plexguide network
    docker_network:
      name: plexguide

### ---------------- MariaDB Home Assistant ------------------- ###
  - name: Setup MariaDB for Home Assistant
    docker_container:
      name: db_homeassistant
      image: linuxserver/mariadb
      pull: yes
      env:
        PUID: "1000"
        PGID: "1000"
        MYSQL_ROOT_PASSWORD: "PcwJ9Qd5DT"
        MYSQL_DATABASE: "homeassistant"
        MYSQL_USER: "homeassistant"
        MYSQL_PASSWORD: "homeassistant"
        TZ: "America/Los_Angeles"
        com.centurylinklabs.watchtower.enable: "true"
      networks:
        - name: plexguide
          aliases:
            - db_homeassistant
      volumes:
        - /opt/appdata/db_homeassistant:/config
      restart_policy: unless-stopped
      state: started

### ---------------- Home Assistant ------------------- ###
  - name: Setup Home Assistant
    docker_container:
      name: home-assistant
      image: homeassistant/home-assistant
      pull: yes
      volumes:
        - /opt/appdata/homeassistant:/config
        - /etc/localtime:/etc/localtime:ro
      env:
        com.centurylinklabs.watchtower.enable: "true"
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: "Host:home.wooster.xyz,home-assistant.wooster.xyz"
        traefik.port: "8123"
        traefik.docker.network: "plexguide"
      ports:
        - "8123:8123"
        # - "8989:8989"
      networks:
        - name: plexguide
          aliases:
            - home-assistant
      restart_policy: unless-stopped
      state: started
      purge_networks: yes

### ---------------- MariaDB Nextcloud ------------------- ###
  - name: Setup MariaDB for Nextcloud
    docker_container:
      name: db_nextcloud
      image: linuxserver/mariadb
      pull: yes
      env:
        PUID: "1000"
        PGID: "1000"
        MYSQL_ROOT_PASSWORD: "PcwJ9Qd5DT"
        MYSQL_DATABASE: "nextcloud"
        MYSQL_USER: "nextcloud"
        MYSQL_PASSWORD: "nextcloud"
        TZ: "America/Los_Angeles"
        com.centurylinklabs.watchtower.enable: "true"
      networks:
        - name: plexguide
          aliases:
            - db_nextcloud
      volumes:
        - /opt/appdata/db_nextcloud:/config
      restart_policy: unless-stopped
      state: started

### ---------------- Nextcloud ------------------- ###
  - name: Setup Nextcloud
    docker_container:
      name: nextcloud
      image: linuxserver/nextcloud
      pull: yes
      volumes:
        - /opt/appdata/nextcloud:/config
        - /mnt/fillmore/nextcloud:/data
      env:
        com.centurylinklabs.watchtower.enable: "true"
      labels:
        traefik.enable: "true"
        traefik.protocol: "https"
        traefik.frontend.redirect.entryPoint: "https"
        traefik.frontend.rule: "Host:nextcloud.wooster.xyz"
        traefik.port: "443"
      networks:
        - name: plexguide
          aliases:
            - nextcloud
      restart_policy: unless-stopped
      state: started

### ------------------ Samba --------------------###
  - name: Setup Samba
    docker_container:
      name: samba
      image: dperson/samba
      pull: yes
      volumes:
        - /mnt/fillmore:/jarvis
      env:
        USERID: "1000"
        GROUPID: "1000"
        TZ: "America/Los_Angeles"
        NMBD: "True"
        RECYCLE: "False"
      ports:
        # - "137:137/udp"
        # - "137:138/udp"
        - "139:139/tcp"
        - "445:445/tcp"
      networks:
        - name: plexguide
          aliases:
            - samba
      restart_policy: unless-stopped
      state: started

### ------------------ Sonarr --------------------###
  - name: Setup Sonarr
    docker_container:
      name: sonarr
      image: linuxserver/sonarr
      pull: yes
      volumes:
        - /mnt:/mnt
        - /opt/appdata/sonarr:/config
      env:
        PUID: "1000"
        GUID: "1000"
        TZ: "America/Los_Angeles"
        com.centurylinklabs.watchtower.enable: "true"
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: "Host:sonarr.wooster.xyz"
        traefik.port: "8989"
        traefik.docker.network: "plexguide"
      ports:
        - "8989:8989"
      networks:
        - name: plexguide
          aliases:
            - sonarr
      restart_policy: unless-stopped
      state: started

### ------------------ Radarr --------------------###
  - name: Setup Radarr
    docker_container:
      name: radarr
      image: linuxserver/radarr
      pull: yes
      volumes:
        - /mnt:/mnt
        - /opt/appdata/radarr:/config
      env:
        PUID: "1000"
        GUID: "1000"
        TZ: "America/Los_Angeles"
        com.centurylinklabs.watchtower.enable: "true"
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: "Host:radarr.wooster.xyz"
        traefik.port: "7878"
        traefik.docker.network: "plexguide"
      ports:
        - "7878:7878"
      networks:
        - name: plexguide
          aliases:
            - radarr
      restart_policy: unless-stopped
      state: started

### ------------------ Tautulli --------------------- ###
  - name: Setup Tautulli
    docker_container:
      name: tautulli
      image: linuxserver/tautulli
      pull: yes
      volumes:
        - /opt/appdata/plex/database/Library/Application Support/Plex Media Server/Logs:/logs
        - /opt/appdata/tautulli/scripts:/scripts
        - /opt/appdata/tautulli:/config
      env:
        PUID: "1000"
        PGID: "1000"
        TZ: "America/Los_Angeles"
        com.centurylinklabs.watchtower.enable: "true"
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: "Host:tautulli.wooster.xyz"
        traefik.port: "8181"
        traefik.docker.network: "plexguide"
      ports:
        - "8181:8181"
      networks:
        - name: plexguide
          aliases:
            - tautulli
      restart_policy: unless-stopped
      state: started

### ------------------ Duplicati -------------------- ###
  - name: Setup Duplicati
    docker_container:
      name: duplicati
      image: linuxserver/duplicati
      pull: yes
      volumes:
        - /mnt:/mnt
        - /opt/appdata/duplicati:/config
      env:
        PUID: "1000"
        GUID: "1000"
        TZ: "America/Los_Angeles"
        com.centurylinklabs.watchtower.enable: "true"
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: "Host:duplicati.wooster.xyz"
        traefik.port: "8200"
        traefik.docker.network: "plexguide"
      networks:
        - name: plexguide
          aliases:
            - duplicati
      restart_policy: unless-stopped
      state: started

### ------------------ OpenVPN -----------------------###
  - name: Setup OpenVPN-AS
    docker_container:
      image: linuxserver/openvpn-as
      name: openvpn-as
      pull: yes
      capabilities:
        - NET_ADMIN
      env:
        PUID: "1000"
        PGID: "1000"
        TZ: "America/Los_Angeles"
        com.centurylinklabs.watchtower.enable: "true"
      volumes:
        - /opt/appdata/openvpn-as:/config
      networks:
        - name: plexguide
          aliases:
            - openvpn
      labels:
#        traefik.frontend.redirect.entryPoint: "https"
#        traefik.protocol: "https"
        traefik.enable: "true"
        traefik.frontend.rule: "Host:openvpn.wooster.xyz"
        traefik.port: "943"
        traefik.docker.network: "plexguide"
      ports:
        - 943:943
        - 9443:9443
        - 1194:1194/udp
      restart_policy: unless-stopped
      state: started

### ------------------ Watchtower --------------------###
  - name: Setup Watchtower
    docker_container:
      name: watchtower
      image: v2tec/watchtower
      pull: yes
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /etc/localtime:/etc/localtime:ro
      command: "--debug --cleanup --interval 1800"
#      env:
#        REPO_USER: ""
#        REPO_PASS: ""
      networks:
        - name: plexguide
          aliases:
            - watchtower
      restart_policy: unless-stopped
      state: started
