- hosts: localhost
  gather_facts: False
  tasks:

  - name: Create plexguide network
    docker_network:
      name: plexguide

### ---------------- MariaDB Home Assistant ------------------- ###
  - name: Setup MariaDB for Home Assistant
    docker_container:
      name: db_homeassistant
      image: linuxserver/mariadb
      pull: yes
      env:
        PUID: "1000"
        PGID: "1000"
        MYSQL_ROOT_PASSWORD: "PcwJ9Qd5DT"
        MYSQL_DATABASE: "homeassistant"
        MYSQL_USER: "homeassistant"
        MYSQL_PASSWORD: "homeassistant"
        TZ: "America/Los_Angeles"
        com.centurylinklabs.watchtower.enable: "true"
      networks:
        - name: plexguide
          aliases:
            - db_homeassistant
      volumes:
        - /opt/appdata/db_homeassistant:/config
      restart_policy: unless-stopped
      state: started

### ---------------- Home Assistant ------------------- ###
  - name: Setup Home Assistant
    docker_container:
      name: home-assistant
      image: homeassistant/home-assistant
      pull: yes
      volumes:
        - /opt/appdata/homeassistant:/config
      env:
        com.centurylinklabs.watchtower.enable: "true"
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: "Host:home.wooster.xyz,home-assistant.wooster.xyz"
        traefik.port: "8123"
        traefik.docker.network: "plexguide"
      ports:
        - "8123:8123"
      network_mode: host
      networks:
        - name: plexguide
          aliases:
            - home-assistant
      restart_policy: unless-stopped
      state: started

### ---------------- MariaDB Nextcloud ------------------- ###
  - name: Setup MariaDB for Nextcloud
    docker_container:
      name: db_nextcloud
      image: linuxserver/mariadb
      pull: yes
      env:
        PUID: "1000"
        PGID: "1000"
        MYSQL_ROOT_PASSWORD: "PcwJ9Qd5DT"
        MYSQL_DATABASE: "nextcloud"
        MYSQL_USER: "nextcloud"
        MYSQL_PASSWORD: "nextcloud"
        TZ: "America/Los_Angeles"
        com.centurylinklabs.watchtower.enable: "true"
      networks:
        - name: plexguide
          aliases:
            - db_nextcloud
      volumes:
        - /opt/appdata/db_nextcloud:/config
      restart_policy: unless-stopped
      state: started

### ---------------- Nextcloud ------------------- ###
  - name: Setup Nextcloud
    docker_container:
      name: nextcloud
      image: linuxserver/nextcloud
      pull: yes
      volumes:
        - /opt/appdata/nextcloud:/config
        - /mnt/fillmore/nextcloud:/data
      env:
        com.centurylinklabs.watchtower.enable: "true"
      labels:
        traefik.enable: "true"
        traefik.protocol: "https"
        traefik.frontend.redirect.entryPoint: "https"
        traefik.frontend.rule: "Host:nextcloud.wooster.xyz"
        traefik.port: "443"
      networks:
        - name: plexguide
          aliases:
            - nextcloud
      restart_policy: unless-stopped
      state: started

### ------------------ Samba --------------------###
  - name: Setup Samba
    docker_container:
      name: samba
      image: dperson/samba
      pull: yes
      volumes:
        - /mnt/fillmore:/jarvis
      env:
        USERID: "1000"
        GROUPID: "1000"
        TZ: "America/Los_Angeles"
        NMBD: "True"
        RECYCLE: "False"
      networks:
        - name: plexguide
          aliases:
            - samba
      restart_policy: unless-stopped
      state: started
